### ISSUE TITLE
[FEAT] Need the possibility to add a new user NOT activated to a group

### ISSUE THREAD

**Issue by pierremorin-asi** [passbolt/passbolt_styleguide#20]
When we create a user, we often need to add it to a group.
Currently, it's impossible, as a user that is not activated can't be selected.

**Comment by stripthis** [comment]
Hello,

Thank you for your feedback. Please request new functionalities on the community forum. We use github issues exclusively for bugs. You can find some existing feature request in the backlog, for example:
https://community.passbolt.com/t/i-want-to-be-able-to-assign-users-into-groups-when-i-am-inviting-them/4362/3

**Comment by pierremorin-asi** [comment]
OK, thanks ! Sorry for that !
