### ISSUE TITLE
Context Menu Inaccessible near bottom of screen

### ISSUE THREAD

**Issue by novaclark** [passbolt/passbolt_styleguide#26]
Server:
Passbolt CE 3.8.0
nginx 1.18.0
PHP 7.4.33
Debian 11.5

Browser:
Chrome 107.0.5304.107 (Official Build) (64-bit)
Windows 10 Enterprise 21H2 19044.2251

Observed Behaviour:
When I right-click on an item near the bottom of the page in my web vault, the context menu runs off the bottom of the page. If I try to use the mouse wheel to scroll down, the context menu disappears.

Expected Behaviour:
When I right-click on an item in the web vault, the whole context menu should appear near the mouse pointer and in such a position as to be 

1. entirely visible in the browser window, or
2. scrollable such that all contents of the menu can be seen, if not all at once, or
3. opened in a spawned browser window.

![Capture](https://user-images.githubusercontent.com/106457294/202021050-870fb1f5-0e14-4294-ade6-5773f68434bd.PNG)

**Comment by cedricalfonsi** [comment]
Thanks for you report. 
Internal reference: PB-18371

**Comment by cedricalfonsi** [comment]
Fixed with recent version
