### ISSUE TITLE
Row shading style of passwords alternates when scrolling

### ISSUE THREAD

**Issue by garrettboone** [passbolt/passbolt_styleguide#34]
Firefox 115

When viewing the `/app/passwords` path I have more passwords than can show on the screen.

Reproduce:
- Start at the top of the list
- Scroll down
- Around the moment when the 5th item is at the top of the viewable window, the alternating gray row shading starts to change while scrolling. It creates a flashing effect.
- When starting at the bottom of the list and scrolling upward the flashing is immediate

Inspecting the page shows content of the list is changing and it's at this moment of change that the shading is changing. I think it's related. 

Why are the contents of the table changed as the table is scrolled? I checked Network on the app and extension and I don't see any outgoing calls being made (I thought maybe it was a refreshing feature). I am not understanding the rationale, however,  maybe if two items were removed at a time instead of one it would not do this?

**Comment by Benj1er** [comment]
Hello @garrettboone,

Thank you for your report.
This issue has been noticed on ours side and a follow-up ticket was created on the internal tracker: PB-24632

Best regards

**Comment by cedricalfonsi** [comment]
Fixed with the latest versions.

Thanks again for your report @garrettboone
