### ISSUE TITLE
Error while trying to build custom theme

### ISSUE THREAD

**Issue by jonaszkadziela** [passbolt/passbolt_styleguide#42]
## Problem with Creating a Custom Theme

While trying to create a custom theme based on [the official blog post](https://www.passbolt.com/blog/how-to-create-a-custom-passbolt-theme-with-the-ui-kit), I ran into the following problem:

```
Running "less:theme_custom" (less) task
>> src/less/base/form/input-text.less: [L36:C18] variable @input-hover-background is undefined
```

It seems that the `colors_custom.sample.less` is outdated. Many variables are missing when I compare it with the `colors.less`.

## Steps to Reproduce
1. Install grunt-cli globally: `sudo npm install -g grunt-cli`
2. Clone the repo: `git clone https://github.com/passbolt/passbolt_styleguide.git`
3. Go to the project folder: `cd passbolt_styleguide`
4. Copy the sample theme file: `cp src/less/abstractions/colors_custom.sample.less src/less/abstractions/colors_custom.less`
5. Install dependencies: `npm run dev:storybook:install`
6. Try to build the custom theme: `npm run dev:build:custom-theme` ---> error thrown here

**Comment by Benj1er** [comment]
Hello @jonaszkadziela,

Thank you for your report and using Passbolt.

All the teams are currently working on v5, and this version will change the style and themes.
I'd advise you to wait until v5 is released early next year before customizing the theme, as this will save you having to start all over again.

Here's a link to the first teaser of v5 on the community forum if you want to follow the progress: [https://community.passbolt.com/t/passbolt-v5-teaser-1-icons-share-your-thoughts](https://community.passbolt.com/t/passbolt-v5-teaser-1-icons-share-your-thoughts)

If you'd like to test the changes in advance, a beta version of the extension will be released prior to the stable version and is available on the chrome store: [https://chromewebstore.google.com/detail/passbolt-open-source-pass/khjbppbablpblmcjpfkfmmnmmpjhaiaf](https://chromewebstore.google.com/detail/passbolt-open-source-pass/khjbppbablpblmcjpfkfmmnmmpjhaiaf)

The blog post is deprecated and an update will be made to create a custom theme for v5.

Best regards

**Comment by jonaszkadziela** [comment]
Hi @Benj1er, thank you for the quick response and for sharing these useful resources!
In that case, I will wait for version 5 before creating my custom theme 👍
